# Generated by Django 3.1.3 on 2020-11-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('option1', models.TextField(max_length=30)),
                ('option2', models.TextField(max_length=30)),
                ('option3', models.TextField(max_length=30)),
                ('option1_count', models.IntegerField(default=0)),
                ('option2_count', models.IntegerField(default=0)),
                ('option3_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'PGT_Polls',
            },
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['question'], name='PGT_Polls_questio_13c497_idx'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='poll',
            order_with_respect_to='question',
        ),
    ]
